// Reserved words in Microsoft's DAX / MDX grammar. daxlib's compiler rejects a
// parameter or VAR identifier that collides with one of these (case-insensitively),
// even though it reads like an ordinary name — e.g. "Table" and "Avg" have both
// been rejected in real daxlib PR review (see docs/daxlib-formatting-guide.md).
//
// Source: https://gregdeckler.com/2024/03/15/into-the-bowels-of-dax-reserved-words/
// This list is NOT guaranteed exhaustive — daxlib's actual grammar is the source
// of truth. If a reviewer flags an identifier that isn't caught here, add it.
const RESERVED_WORDS_LIST = [
    "ABSOLUTE", "ADD", "ADDCOLUMNS", "AFTER", "AGGREGATE", "ALL", "ALLEXCEPT", "ALLMEMBERS",
    "ALLNOBLANKROW", "ALLSELECTED", "ALTER", "AND", "APPLICATION", "AS", "ASC", "ASCENDANTS", "AT",
    "AVERAGE", "AVERAGEA", "AVERAGEX", "AVG", "AXIS", "BASC", "BDESC", "BEFORE", "BEGIN", "BINARY",
    "BLANK", "BOOLEAN", "BOTTOMCOUNT", "BOTTOMPERCENT", "BOTTOMSUM", "BY", "CACHE", "CALCULATE",
    "CALCULATETABE", "CALCULATION", "CALCULATIONCURRENTPASS", "CALCULATIONS",
    "CALCULATIOPASSVALUE", "CALL", "CASE", "CELL", "CHAPTERS", "CHILDREN", "CLEAR", "CLOSE",
    "CLOSINGBALANCEMONTH", "CLOSINGBALANCEQUARTER", "CLOSINGBALANCEYAR", "CLOSINGPERIOD",
    "COALESCEEMPTY", "COLUMN", "COLUMNS", "COMMIT", "CONTAINS", "CORRELATION", "COUNT", "COUNTA",
    "COUNTAX", "COUNTBLANK", "COUNTROWS", "COUNTX", "COUSIN", "COVARIANCE", "COVARIANCEN",
    "CREATE", "CROSSJOIN", "CUBE", "CURRENT", "CURRENTCUBE", "CURRENTMEMBER", "CUSTOMDATA",
    "DATATABLE", "DATE", "DATESBETWEEN", "DATESINPERIOD", "DATESMTD", "DATESQTD", "DATESYTD",
    "DEFAULTMEMBER", "DEFINE", "DELETE", "DENSIFY", "DESC", "DESCD", "DESCENDANTS", "DESCRIPTION",
    "DIMENSION", "DIMENSIONS", "DISTINCT", "DISTINCTCOUNT", "DIVIDE", "DOUBLE", "DRILLDOWNLEVEL",
    "DRILLDOWNLEVELBOTTOM", "DRILLDOWNLEVELTOP", "DRILLDOWNMEMBER", "DRILLDOWNMEMBERBOTTOM",
    "DRILLDOWNMEMBERTOP", "DRILLUPLEVEL", "DRILLUPMEMBER", "DROP", "EARLIER", "EARLIEST", "ELSE",
    "EMPTY", "END", "ENDOFMONTH", "ENDOFQUARTER", "ENDOFYEAR", "ERROR", "EVALUATEANDLOG",
    "EVALULATE", "EXCEPT", "EXCLUDEEMPTY", "EXISTS", "EXTRACT", "FALSE", "FILTER", "FIRSTCHILD",
    "FIRSTDATE", "FIRSTNONBLANK", "FIRSTSIBLING", "FOR", "FORMAT", "FREEZE", "FROM", "GENERATE",
    "GENERATEALL", "GLOBAL", "GROUP", "GROUPING", "HASONEFILTER", "HASONEVALUE", "HAVING", "HEAD",
    "HIDDEN", "HIERARCHIZE", "HIERARCHY", "IF", "IIF", "INCLUDEEMPTY", "INSERT", "INTERSECT",
    "INTO", "IS", "ISANCESTOR", "ISEMPTY", "ISFILTERED", "ISGENERATION", "ISLEAF", "ISSIBLING",
    "ISSUBTOTAL", "ITEM", "JOIN", "KEEPFILTERS", "KEY", "LAG", "LASTCHILD", "LASTDATE",
    "LASTNONBLANK", "LASTPERIODS", "LASTSIBLING", "LEAD", "LEAVES", "LEVEL", "LEVELS",
    "LINKMEMBER", "LINREGINTERCEPT", "LINREGPOINT", "LINREGR2", "LINREGSLOPE", "LINREGVARIANCE",
    "LOG", "LONG", "LOOKUPCUBE", "LOOKUPVALUE", "MAX", "MAXA", "MAXX", "MEASURE", "MEDIAN",
    "MEMBER", "MEMBERS", "MEMBERTOSTR", "MIN", "MINA", "MINX", "MOVE", "MPARAMETER", "MTD", "NAME",
    "NAMETOSET", "NEST", "NEXTDAY", "NEXTMEMBER", "NEXTMONTH", "NEXTQUARTER", "NEXTYEAR", "NON",
    "NONEMPTYCROSSJOIN", "NOT", "NULL", "OF", "ON", "OPEN", "OPENINGBALANCEMONTH",
    "OPENINGBALANCEQUARTER", "OPENINGBALANCEYEAR", "OPENINGPERIOD", "OPENQUERY", "OPENROWSET",
    "OR", "ORDER", "PAGES", "PARALLELPERIOD", "PARENT", "PASS", "PATH", "PATHCONTAINS", "PATHITEM",
    "PATHITEMREVERSE", "PATHLENGTH", "PERCENT", "PERIODSTODATE", "POST", "PREDICT", "PREVIOUSDAY",
    "PREVIOUSMONTH", "PREVIOUSQUARTER", "PREVIOUSYEAR", "PREVMEMBER", "PROPERTIES", "PROPERTY",
    "QTD", "RANK", "RANKX", "READ", "RECURSIVE", "REFRESH", "RELATED", "RELATEDTABLE", "RELATIVE",
    "RETURN", "ROLLBACK", "ROLLUP", "ROLLUPCHILDREN", "ROLLUPGROUP", "ROOT", "ROW", "ROWS",
    "SAMEPERIODLASTYEAR", "SCOPE", "SECTIONS", "SELECT", "SELF", "SESSION", "SET", "SETTOARRAY",
    "SETTOSTR", "SHAPE", "START", "STARTOFMONTH", "STARTOFQUARTER", "STARTOFYEAR", "STDDEV",
    "STDDEVP", "STDEV", "STDEVP", "STORAGE", "STRIPCALCULATEDMEMBERS", "STRTOMEMBER", "STRTOSET",
    "STRTOTUPLE", "STRTOVAL", "STRTOVALUE", "SUBSET", "SUM", "SUMMARIZE", "SUMX", "SWITCH",
    "TABLE", "TAIL", "TEXT", "THEN", "THIS", "TO", "TOGGLEDRILLSTATE", "TOP", "TOPCOUNT", "TOPN",
    "TOPPERCENT", "TOPSUM", "TOTALMTD", "TOTALQTD", "TOTALS", "TOTALYTD", "TRAN", "TRANSACTION",
    "TRUE", "TUPLETOSTR", "TYPE", "UNION", "UNIQUE", "UNIQUENAME", "UPDATE", "USE",
    "USERELATIONSHIP", "USERNAME", "VALIDMEASURE", "VALUE", "VALUES", "VAR", "VARIANCE",
    "VARIANCEP", "VARP", "VERSION", "VISUAL", "VISUALTOTALS", "WHEN", "WHERE", "WITH", "WTD",
    "XOR", "YTD",
];

export const DAX_RESERVED_WORDS: ReadonlySet<string> = new Set(
    RESERVED_WORDS_LIST.map((w) => w.toUpperCase())
);
